### ISSUE TITLE
`Batch.size` is a `TextField`

### ISSUE THREAD

**Issue by Samuel-Therrien-Beslogic** [BesLogic/releaf-canopeum#139]
In https://github.com/BesLogic/releaf-canopeum/pull/138#discussion_r1594766580 I noticed that  `Batch.objects.create` takes a `size` param of type `str`. This seems incorrect, let's update the DB model type to something number-based. (integer is fine)

**Comment by NicolasDontigny** [comment]
Seems to be fixed in the current code, can we close this issue?

**Comment by Samuel-Therrien-Beslogic** [comment]
Fixed by https://github.com/BesLogic/releaf-canopeum/pull/135
