### ISSUE TITLE
As a User, I should see the social page layout

### ISSUE THREAD

**Issue by BesOlivierBouchard** [BesLogic/releaf-canopeum#19]
## Description

Under the navigation: `/map/{siteId}`

The following layout is expected:

- Site Header
- Left Column
  - Announcement
  - Contact
- Right Column
  - List of Posts

A `col-4`, `col-8` width for the left and right columns should be used.

## Expected Result

![Image](https://github.com/BesLogic/releaf-canopeum/assets/93934995/6b4f49aa-e32a-4bd7-9fd8-4ac43190e8f3)

**Comment by yanbes** [comment]
Translation FR: 

- Announcement: Annonce
- Follow: Suivre
- Sponsors: Commanditaires

**Comment by yanbes** [comment]
Mouse over sur les icônes en bas à gauche des posts:

Feuille: 125 Leaf Likes / 125 Feuilles de partages
Commentaires: 87 Replies / 87 Réponses
Partage (nous n'aurons pas le nombre donc c'est un bouton) : Share / Partager

**Comment by sam9291** [comment]
Layout merged in PR https://github.com/BesLogic/releaf-canopeum/pull/66

Individual component carts will be implemented in the following user stories
