### ISSUE TITLE
As a User, I should see the social page header for a site

### ISSUE THREAD

**Issue by BesOlivierBouchard** [BesLogic/releaf-canopeum#20]
## Description

Under the navigation: `/map/{siteId}`

The following information should be displayed in the header:

- Image
- Site Name
- Site Type
- Brief Presentation
- Sponsors

Depending on the role on the top right of the header should be displayed:

- Admin: A switch for the map visible
- User: A follow button
- Visitor: Nothing

### Admin

![Image](https://github.com/BesLogic/releaf-canopeum/assets/93934995/5911e124-48e1-4412-950f-e14dd9b961a1)

### User

![Image](https://github.com/BesLogic/releaf-canopeum/assets/93934995/e08e1d60-0ac1-4b1f-becd-d0583e5cdda2)
### Visitor

![Image](https://github.com/BesLogic/releaf-canopeum/assets/93934995/1a890733-767d-4e92-965b-bb1c8acf35da)

**Comment by yanbes** [comment]
Translation to FR: 
- Follow: Suivre

**Comment by sam9291** [comment]
@BesOlivierBouchard is the default bootstrap theme for switches ok or we want to have exactly the ones in the mockups?


![Image](https://github.com/BesLogic/releaf-canopeum/assets/5232883/34eb908c-b346-4b31-a400-c38f855ddfb7)

**Comment by BesOlivierBouchard** [comment]
> [@BesOlivierBouchard](https://github.com/BesOlivierBouchard) is the default bootstrap theme for switches ok or we want to have exactly the ones in the mockups?
> 
> ![Image](https://private-user-images.githubusercontent.com/5232883/316363757-230f45c7-3649-467e-a98e-3a900ddacb4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjM1MzgsIm5iZiI6MTcxMTQ2MzIzOCwicGF0aCI6Ii81MjMyODgzLzMxNjM2Mzc1Ny0yMzBmNDVjNy0zNjQ5LTQ2N2UtYTk4ZS0zYTkwMGRkYWNiNGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjZUMTQyNzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWY1MzExZjZkN2JkMzUyMDc3OTA5Mjg3MzFhNjZmNWYxODFlOGU1MGE3ZDNmOGU2MTQ4NTBkZmUyM2I3ZGU3ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NoMHrLyjxvLeGlLuoXluZp8zwkn8wqfR3_Us_PFrhRw)

The bootstrap theme will be adapted, but we should use the bootstrap look: 
https://getbootstrap.com/docs/5.0/forms/checks-radios/#switches
