### ISSUE TITLE
As a User, I should see the Announcement card

### ISSUE THREAD

**Issue by BesOlivierBouchard** [BesLogic/releaf-canopeum#21]
## Description

Under the navigation: `/map/{siteId}`

The announcement card should be display in the left column with the following information:

- Body
- Link

A button on the top right of card is only visible for admins.

### Admin

![Image](https://github.com/BesLogic/releaf-canopeum/assets/93934995/5d5698c9-5f64-45e2-8fe0-4a9a057fc998)

### User & Visitor

![Image](https://github.com/BesLogic/releaf-canopeum/assets/93934995/a56c3f22-2f49-4dde-aa81-bd5ad2c89226)

**Comment by yanbes** [comment]
Translation to FR: 
- Announcement: Annonce
