### ISSUE TITLE
As a dev I want to fix UI/UX issues

### ISSUE THREAD

**Issue by bes-alielzein** [BesLogic/releaf-canopeum#211]
1. ~~Super admin home page is empty.~~ https://github.com/BesLogic/releaf-canopeum/issues/231
As we already have 4 sites in the app, the home page of the super admin should display all the latest posts from these 4 sites, because the Super admin automatically follows all sites. 
![Image](https://github.com/user-attachments/assets/f48835e5-4ee1-457a-84c8-1b086e71a514)

2. ~~Inconsistent background color (/Sites)~~ https://github.com/BesLogic/releaf-canopeum/issues/212
The background color of all the cards should be consistent, the right color code is:  #FFFAF5 
![Image](https://github.com/user-attachments/assets/a9f7c16a-59fb-4491-a8a8-aaf763183c66)

3. ~~Wrong button label (Popup-Create Site)~~ https://github.com/BesLogic/releaf-canopeum/issues/214
The label of the green button should be “Submit”, not “Subscribe”. 
![Image](https://github.com/user-attachments/assets/cd2fe235-69b4-43e9-8d11-f0f41cc4d599)

4. ~~Users can’t manually input the number of trees.(Popup-Create Site)~~ https://github.com/BesLogic/releaf-canopeum/issues/216
Users need an editable input bar to enter the number of trees.  
Suggestion: we can use the same input bar of the GPS Coordinates. 
![Image](https://github.com/user-attachments/assets/d50b3111-8031-4277-9a82-017803a5ebad)
![Image](https://github.com/user-attachments/assets/253ccf3d-a39a-4fa5-813d-eb245db6e40b)

5. ~~Users can’t create a new site. (Popup-Create Site)~~ https://github.com/BesLogic/releaf-canopeum/issues/10 Already fixed, not sure when. Maybe https://github.com/BesLogic/releaf-canopeum/pull/194
After completing the form, clicking on the “Submit” button will only close the popup, no new site created. 
![Image](https://github.com/user-attachments/assets/39b1fa46-1b81-4a60-ace4-37bdd421edc2)

6. ~~Error feedback not clear. (Popup-create a new batch)~~ https://github.com/BesLogic/releaf-canopeum/issues/240
The error feedback is not clear, there are no explanation of what users did wrong while completing the form. 
![Image](https://github.com/user-attachments/assets/54948c71-b8e6-4b85-bb5f-64b9d13d2c81)

7. ~~Users can’t edit or delete an existing batch. (Batch Tracking table)~~ https://github.com/BesLogic/releaf-canopeum/issues/218
Suggestion: make the batch names clickable, clicking on a batch name will open a single selection dropdown with 2 options: “Edit Batch” or “Delete Batch”. Clicking on “Edit Batch” will open the same popup “Create a new batch” with prefilled form. Clicking on the “Delete Batch” will delete the batch from the table. 
![Image](https://github.com/user-attachments/assets/ceb12245-5424-47d4-88fd-c86e199ebe9e)

8. ~~A newly added batch should be displayed at the first column of the table instead of the last column. (Batch tracking table)~~ Already fixed, idk when 
![Image](https://github.com/user-attachments/assets/f6b170c0-cbfe-4e2c-89d1-d14d65b90e08)

9. ~~Site image cannot be displayed. (Site social page)~~ Already fixed, maybe by https://github.com/BesLogic/releaf-canopeum/pull/233
![Image](https://github.com/user-attachments/assets/de41d05f-b813-478c-9bc4-96c481a0e7ac)

10. ~~Image upload button no response (Site social page).~~ Already fixed
![Image](https://github.com/user-attachments/assets/956869e2-032a-4806-8102-31b7855562f6)

11. ~~Announcement card/Contact card edit button no response. (Site social page)~~ Already fixed 
![Image](https://github.com/user-attachments/assets/277001d9-a4cc-476e-9e8a-b77ef8cf0c66)

12. ~~No pins on the map. (Map page)~~ https://github.com/BesLogic/releaf-canopeum/issues/17 incorrect pins fixed by https://github.com/BesLogic/releaf-canopeum/pull/270
![Image](https://github.com/user-attachments/assets/f2738bd3-46b6-4051-b2ef-97273aa98864)

**Comment by Samuel-Therrien-Beslogic** [comment]
We need to split these into proper individual issues so we can track progress. Some of these are more than simple UI/UX issues that can be punted for later.
