### ISSUE TITLE
As a user, I want to be able to input the number of trees directly

### ISSUE THREAD

**Issue by bes-alielzein** [BesLogic/releaf-canopeum#216]
Users can’t manually input the number of trees.(Popup-Create Site) 
Users need an editable input bar to enter the number of trees.  
Suggestion: we can use the same input bar of the GPS Coordinates. 
![Image](https://github.com/user-attachments/assets/5b6f1050-c388-4315-8b8d-a4988dfce4ae)
![Image](https://github.com/user-attachments/assets/17c3bc65-612c-4ac7-b738-318d9b3f1868)

**Comment by Samuel-Therrien-Beslogic** [comment]
Agreed! All for accessibility !
