### ISSUE TITLE
As an User, I should see the additional Widgets

### ISSUE THREAD

**Issue by BesOlivierBouchard** [BesLogic/releaf-canopeum#23]
## Description

Under the navigation: `/sites/{siteId}/social`

Below the Contact card should be displayed additional widgets.

Each Widget is composed of a Title and a Body.

A button on the top right of the card to edit/delete is only visible for admins.

**Comment by Samuel-Therrien-Beslogic** [comment]
@NicolasDontigny @BesOlivierBouchard  When was this completed ?

**Comment by Samuel-Therrien-Beslogic** [comment]
Closed by #147

![image](https://github.com/user-attachments/assets/f201499d-3142-4345-bc9f-f833edb03e77)
