### ISSUE TITLE
Total number of plants should be calculated automatically

### ISSUE THREAD

**Issue by NicolasDontigny** [BesLogic/releaf-canopeum#241]
In the Batch Form, the field "Number of Plants" should actually not be an input, but just a text displayed below the field "Number of Trees per Species". It should simply calculate the sum of all number of trees for all selected species.

Similarly, the field "Total number of seeds collected" should also be a display of the sum for all seeds selected in the dropdown "Number of Seeds Collected per Species"

**Comment by Samuel-Therrien-Beslogic** [comment]
Started work in https://github.com/BesLogic/releaf-canopeum/tree/feature/241-Total-number-of-plants-should-be-calculated-automatically
