### ISSUE TITLE
Update some BatchDetail property serializers

### ISSUE THREAD

**Issue by NicolasDontigny** [BesLogic/releaf-canopeum#247]
Update some BatchDetail property serializers to simplify the models and prevent the wrong ids to be referenced

ie: BatchSupportedSpeciesSerializer has a property named "id", but it is actually the tree_type id. This serializer can be removed and TreeTypeSerializer can be used instead to reference the batch's supported species

**Comment by Samuel-Therrien-Beslogic** [comment]
CLosed by https://github.com/BesLogic/releaf-canopeum/pull/248
