### ISSUE TITLE
As an Admin, I should be able to create new Widgets

### ISSUE THREAD

**Issue by BesOlivierBouchard** [BesLogic/releaf-canopeum#25]
## Description

Under the navigation: `/home/{siteId}` 

Admins should see a card with the "+ Add a New Widget" button.

Clicking on the button should display a form with a title and body input.

## Expected Result

![Image](https://github.com/BesLogic/releaf-canopeum/assets/93934995/e14fe9b5-998b-4341-bb7b-5f73b03da116)

**Comment by yanbes** [comment]
Translation to FR: 
- Add a New Widget: Ajouter une nouvelle composante
- Widget Title: Titre de la composante
- Cancel: Annuler
- Save: Enregistrer
- 100 Words Maximum: 100 mots maximum
-

**Comment by Samuel-Therrien-Beslogic** [comment]
Closed by https://github.com/BesLogic/releaf-canopeum/pull/147
