### ISSUE TITLE
As a User, I should be able to see the comments of a post

### ISSUE THREAD

**Issue by BesOlivierBouchard** [BesLogic/releaf-canopeum#30]
## Description

Under the navigation: `/map/{siteId}`

Clicking on the comment button of a post, should display a modal with the following layout:

- New Comment section
- Comment section header + comment count
- List of comments

## Expected Result

![Image](https://github.com/BesLogic/releaf-canopeum/assets/93934995/af816321-d03a-47c7-bfc6-d78ad5bbf5ad)

**Comment by yanbes** [comment]
Traduction vers le Francais: 
- Comments : Commantaires
- Send: Envoyer
- Leave a comment: Laisser un commentaire
- 100 Words Maximum: 100 mots maximum
