### ISSUE TITLE
As User, I should be able to write down a comment on a post

### ISSUE THREAD

**Issue by BesOlivierBouchard** [BesLogic/releaf-canopeum#31]
## Description

Under the navigation: `/map/{siteId}`

The following information is displayed to create a new comment:

- Section header + Send button
- Textarea for the comment body

## Expected Result

![Image](https://github.com/BesLogic/releaf-canopeum/assets/93934995/10f2afbd-9ecd-4df6-9e3f-b9ae5d028ec9)

**Comment by yanbes** [comment]
Traduction vers le Francais:

Send: Envoyer
Leave a comment: Laisser un commentaire
100 Words Maximum: 100 mots maximum
