### ISSUE TITLE
As a user, I need an endpoint to update the anoucement part of one of my specific site

### ISSUE THREAD

**Issue by AlexGeorge29** [BesLogic/releaf-canopeum#45]
## Description

An endpoint allowing the user to update the content of the anoncment part of on of his site should be available.

## expected results

- the route route should be social/sites/:siteId/announcement
- the method should be: PATCH
- Only  anouncment of a user's site can be updated
- The response should include appropriate status codes.
- the endpoint should include a quick description after declaration as a comment in the code

**Comment by Samuel-Therrien-Beslogic** [comment]
Closed by #199
