### ISSUE TITLE
As a user, I need an endpoint to update the contact part of one of my specific site

### ISSUE THREAD

**Issue by AlexGeorge29** [BesLogic/releaf-canopeum#46]
## Description

An endpoint allowing the user to update the content of the contact part of on of his site should be available.

## Expected results

- the route route should be social/sites/:siteId/contact
- the method should be: PATCH
- Only anouncment of a user's site can be updated
- The response should include appropriate status codes.
- the endpoint should include a quick description after declaration as a comment in the code

**Comment by Samuel-Therrien-Beslogic** [comment]
Closed by #199
