### ISSUE TITLE
As a user, I need an endpoint to update a specific widget associated to a widget

### ISSUE THREAD

**Issue by AlexGeorge29** [BesLogic/releaf-canopeum#48]
## Description

An endpoint allowing the user to update a specific widget associated to a widget should be available

## Expected Results

- the route route should be social/sites/:siteId/widgets/:id
- the method should be: PATCH
- Only anouncment of a user's site can be updated
- The response should include appropriate status codes.
- the endpoint should include a quick description after declaration as a comment in the code

**Comment by Samuel-Therrien-Beslogic** [comment]
Closed by #147
