### ISSUE TITLE
As a user, I need an endpoint to delete a widget associated to one of my site

### ISSUE THREAD

**Issue by AlexGeorge29** [BesLogic/releaf-canopeum#49]
## Description

An enpoint allowing the user to delete a widget created by himself associated to one of its site should be available.

## Expected Results

- the route route should be social/sites/:siteId/widgets/:id
- the method should be: DELETE
- Only anouncment of a user's site can be updated
- The response should include appropriate status codes.
- the endpoint should include a quick description after declaration as a comment in the code

**Comment by Samuel-Therrien-Beslogic** [comment]
Closed by #147
