### ISSUE TITLE
As a Mega Admin, I should be able to Edit a site from its summary card

### ISSUE THREAD

**Issue by NicolasDontigny** [BesLogic/releaf-canopeum#85]
Description
Clicking on the "..." of a site summary card should display the actions available regarding this site.
In this story, we simply want the "Edit a site" to point to the edit form

Expected Result
![Image](https://github.com/BesLogic/releaf-canopeum/assets/45007853/e54b3c12-fd5c-4ed7-8c36-20b1f33858a0)

**Comment by Samuel-Therrien-Beslogic** [comment]
Closed by #132
